### ISSUE TITLE
All videos page

### ISSUE THREAD

**Issue by asidelnik** [asidelnik/document-violence-dashboard#17]
### Tasks

- [ ] TDD - create tests before each task
- [ ] **Filters bar** - #26 
- [ ] **useGetVideos** - fix the AbortController
- [ ] **Videos grid**
  - [ ] Create more fake DB data
  - [ ] Infinite scroll
- [ ] **Video Item Info**
  - [ ] Hoverable events list
  - [ ] Button to relate a video to events - opens a right side dialog with a filterable list of events (what data).
  - [ ] Map button
- [ ] Page layout design - horizontal or vertical filters?
- [ ] Multiple video item select - to update status or event at once
