### ISSUE TITLE
Video item - set event

### ISSUE THREAD

**Issue by asidelnik** [asidelnik/document-violence-dashboard#41]
### Basic tasks
- [x] Document DB - check if a video should hold multiple events or each event a couple of videos or a connection table?
  - [x] For design simplicity - an event can have multiple videos. A video can have 1 event.
- [x] Update DB json
  - [x] An event has an array of videos
  - [x] A video has Event | null
  - [x] Update all ids to strings (json-server specification)

- [x] Actions
  - [x] GET - autocomplete events (latest)
    - [x] Server code
    - [x] Client request
  - [x] POST - set event to video
    - [x] Server code - test
    - [x] Client request

- [x] **UI - Event AutoComplete**
  - [x] Use MUI CheckboxesTags
  - [x] Getting a bug - MUI: A component is changing the uncontrolled value state of Autocomplete to be controlled.
    - [x] Solution - [controlled state](https://mui.com/material-ui/react-autocomplete/#controlled-states) - useMemo checkedOption

### UI Improvements
  - #54
  - #53 

### Testing
Need to move testing task to a new issue - must test e2e - client - server - db

**Comment by asidelnik** [comment]
Test

**Comment by asidelnik** [comment]
- [ ] Fix server according to flowchart logic
![Image](https://github.com/user-attachments/assets/1ae28997-7c36-46f8-aa9b-7ab7eb322f3b)

**Comment by asidelnik** [comment]
### Tasks to complete in task 60
- [ ] Event update - should show on screen 
- [ ] Remove Event from Video - not working

#60

**Comment by asidelnik** [comment]
Completed & Merged in #61
