### ISSUE TITLE
Events - table filtering

### ISSUE THREAD

**Issue by asidelnik** [asidelnik/document-violence-dashboard#49]
### Filter fields
- [x] Time period - date picker from Videos filtering
- [x] Priority - multi select
- [x] Free text - MUi

### Tasks
- [x] Event filters context
- [x] Server - update events request - add filtering conditions
- [x] Events page - styling updates
- [x] Filters - add free text field - title & desc - MUI
  - [x] Free text filter - send less filter server requests - debounce or abort:
    - [x] Debounce - wait 3 milliseconds before sending a request. If another is sent it cancels the previous one with useEffect cleanup 
AbortController - cancel previous requests - not implemented

- [x] Test table filters with server data
