### ISSUE TITLE
Implement React Query across other fetching code

### ISSUE THREAD

**Issue by asidelnik** [asidelnik/document-violence-dashboard#60]
### Tasks
- [x] Create branch from main
- [x] Merge #41 into this branch.
- [ ] Complete this branch tasks

### React Query usage
- [x] Get Events for Video updating
- [x] Update Status
- [x] Update Event

### State Hierarchy Updates
- [x] Move EventsAutocomplete state from VideosGrid up to AllVideosPage

### Will be merged in:
#61

**Comment by asidelnik** [comment]
Completed & Merged in #61
